constants:
  file:
    upload-directory: /home/ubuntu/upload

  oauth2:
    authorized-redirect-uris:
      - http://localhost:5173/fe/redirect
      - http://112.222.157.157:5174/fe/redirect

spring:
  datasource:
    url: jdbc:mariadb://10.0.0.49/greengram
    username: green
    password: green502
    driver-class-name: org.mariadb.jdbc.Driver

  sql:
    init:
      mode: never

